/** io.github.* namespace: no dedicated Hyaecord domain is owned yet, so this is the ID Flathub can verify against the GitHub org without separate domain-ownership proof. */
export const APP_ID = "io.github.Hyaecord.Hyaecord";
export const PRODUCT_NAME = "Hyaecord";

export const DEFAULT_SETTINGS = {
  theme: "system",
  reducedMotion: "system",
  textScale: 1,
  uiScale: 1,
  gamingMode: false,
  firstRunCompleted: false,
  /** Discord's own real Developer Mode setting — adds "Copy ID" to right-click menus on servers/channels/messages/profiles. Off by default, same as stock Discord. */
  developerMode: false,
  integrations: {
    userPFP: true,
    usrBG: true,
    globalBadges: true,
    rpcBridge: true
  },
  selfPinFade: {
    enabled: true,
    delaySeconds: 10
  },
  telemetry: {
    enabled: true,
    anonId: null
  },
  chomper: {
    hidden: [] as Array<{ id: string; type: "guild" | "dm" }>,
    showHidden: false
  },
  serverFolders: [] as Array<{ id: string; name: string; color: string | null; guildIds: string[]; collapsed: boolean }>,
  communityTheme: null,
  /** When on (default), every connected platform's servers show together in one rail, each badged with its platform. When off, the rail shows only `activeSidebarPlatform`. */
  mergeSidebar: true,
  activeSidebarPlatform: "discord" as "discord" | "stoat"
} as const;

export const TELEMETRY_ENDPOINT = "https://hyaecord.vercel.app/api/telemetry";

export const IPC = {
  getSettings: "hyaecord:get-settings",
  setSettings: "hyaecord:set-settings",
  getDesktopEnvironment: "hyaecord:get-de",
  getLocaleStrings: "hyaecord:get-locale",
  getLocale: "hyaecord:get-locale-code",
  themeChanged: "hyaecord:theme-changed",
  discordLoginBrowser: "hyaecord:discord-login-browser",
  discordLogout: "hyaecord:discord-logout",
  discordGetSession: "hyaecord:discord-get-session",
  discordState: "hyaecord:discord-state",
  discordEvent: "hyaecord:discord-event",
  discordFetchMessages: "hyaecord:discord-fetch-messages",
  discordSendMessage: "hyaecord:discord-send-message",
  discordDeleteChannel: "hyaecord:discord-delete-channel",
  discordMuteGuild: "hyaecord:discord-mute-guild",
  discordMuteDm: "hyaecord:discord-mute-dm",
  openExternal: "hyaecord:open-external",
  getCommunityThemes: "hyaecord:get-community-themes",
  isUsingVpn: "hyaecord:is-using-vpn",
  discordGetUserProfile: "hyaecord:discord-get-user-profile",
  getGlobalBadges: "hyaecord:get-global-badges",
  getUserPfpMap: "hyaecord:get-userpfp-map",
  getUserBgMap: "hyaecord:get-usrbg-map",
  getPlugins: "hyaecord:get-plugins",
  setPluginEnabled: "hyaecord:set-plugin-enabled",
  setPluginSetting: "hyaecord:set-plugin-setting",
  pluginToast: "hyaecord:plugin-toast",
  discordSearchGifs: "hyaecord:discord-search-gifs",
  discordSetAvatar: "hyaecord:discord-set-avatar",
  discordSubscribeMembers: "hyaecord:discord-subscribe-members",
  gamingModeState: "hyaecord:gaming-mode-state",
  discordSearchMessages: "hyaecord:discord-search-messages",
  discordToggleEmbedSuppression: "hyaecord:discord-toggle-embed-suppression",
  discordListRelationships: "hyaecord:discord-list-relationships",
  discordSendFriendRequest: "hyaecord:discord-send-friend-request",
  discordAcceptFriendRequest: "hyaecord:discord-accept-friend-request",
  discordBlockUser: "hyaecord:discord-block-user",
  discordRemoveRelationship: "hyaecord:discord-remove-relationship",
  getPluginCommands: "hyaecord:get-plugin-commands",
  runPluginCommand: "hyaecord:run-plugin-command",
  discordListMessagePins: "hyaecord:discord-list-message-pins",
  discordPinMessage: "hyaecord:discord-pin-message",
  discordUnpinMessage: "hyaecord:discord-unpin-message",
  getStickerPacks: "hyaecord:get-sticker-packs",
  discordSendSticker: "hyaecord:discord-send-sticker",
  discordJoinVoice: "hyaecord:discord-join-voice",
  discordLeaveVoice: "hyaecord:discord-leave-voice",
  discordVoiceState: "hyaecord:discord-voice-state",
  getScreenShareSources: "hyaecord:get-screen-share-sources",
  stoatLoginBrowser: "hyaecord:stoat-login-browser",
  stoatLogout: "hyaecord:stoat-logout",
  stoatGetSession: "hyaecord:stoat-get-session",
  stoatState: "hyaecord:stoat-state",
  stoatEvent: "hyaecord:stoat-event",
  stoatFetchMessages: "hyaecord:stoat-fetch-messages",
  stoatSendMessage: "hyaecord:stoat-send-message",
  stoatGetDMs: "hyaecord:stoat-get-dms",
  stoatGetServerMembers: "hyaecord:stoat-get-server-members",
  stoatPinMessage: "hyaecord:stoat-pin-message",
  stoatUnpinMessage: "hyaecord:stoat-unpin-message",
  stoatGetUser: "hyaecord:stoat-get-user",
  getCredits: "hyaecord:get-credits",
  stoatAddReaction: "hyaecord:stoat-add-reaction",
  stoatRemoveReaction: "hyaecord:stoat-remove-reaction",
  stoatEditMessage: "hyaecord:stoat-edit-message",
  stoatDeleteMessage: "hyaecord:stoat-delete-message",
  stoatSearchMessages: "hyaecord:stoat-search-messages",
  stoatGetPinnedMessages: "hyaecord:stoat-get-pinned-messages",
  stoatStartTyping: "hyaecord:stoat-start-typing",
  stoatStopTyping: "hyaecord:stoat-stop-typing",
  stoatSendFriendRequest: "hyaecord:stoat-send-friend-request",
  stoatAcceptFriendRequest: "hyaecord:stoat-accept-friend-request",
  stoatRemoveFriend: "hyaecord:stoat-remove-friend",
  stoatOpenDM: "hyaecord:stoat-open-dm",
  stoatPreviewInvite: "hyaecord:stoat-preview-invite",
  stoatJoinInvite: "hyaecord:stoat-join-invite",
  stoatLeaveServer: "hyaecord:stoat-leave-server",
  stoatCreateServer: "hyaecord:stoat-create-server",
  stoatCreateInvite: "hyaecord:stoat-create-invite",
  stoatGetProfile: "hyaecord:stoat-get-profile",
  stoatGetUnreads: "hyaecord:stoat-get-unreads",
  stoatAckChannel: "hyaecord:stoat-ack-channel",
  stoatEditChannel: "hyaecord:stoat-edit-channel",
  stoatSetDefaultChannelPermissions: "hyaecord:stoat-set-default-channel-permissions",
  stoatSetRoleChannelPermissions: "hyaecord:stoat-set-role-channel-permissions"
} as const;
